import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SocketProvider } from "@/context/socketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <SocketProvider>
        <html lang="en">
          <body className={inter.className}>
            <div className="min-h-screen flex flex-col">{children}</div>
          </body>
        </html>
      </SocketProvider>
    </ClerkProvider>
  );
}
